name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: m0ln1z/my-fastapi-app:latest  

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Загрузка приватного ключа Deploy Key напрямую из файла
    - name: Add Deploy Key to SSH Agent
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-add ~/.ssh/id_rsa.pub

    - name: SSH into server and deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Отладочная информация
          echo "SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}"
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"

          # Деплой
          docker pull m0ln1z/my-fastapi-app:latest
          docker stop my-fastapi-app || true
          docker rm my-fastapi-app || true
          docker run -d --name my-fastapi-app -p 80:80 m0ln1z/my-fastapi-app:latest
