name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Используем последнюю версию для checkout

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t m0ln1z/my-fastapi-app:latest .
        docker push m0ln1z/my-fastapi-app:latest

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        private_key: ${{ secrets.SERVER_SSH_KEY }}  # Используем SSH ключ
        script: |
          # Остановка и удаление старых контейнеров с использованием docker-compose
          docker-compose -f /path/to/your/docker-compose.yml down
          docker-compose -f /path/to/your/docker-compose.yml pull
          docker-compose -f /path/to/your/docker-compose.yml up -d  # Запуск обновленного контейнера
