name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Установка Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Логин в DockerHub (если нужно)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Построение Docker образа
      - name: Build Docker image
        run: docker build -t my-fastapi-app .

      # Запуск Docker контейнера (можно настроить деплой в сервер)
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name fastapi-app my-fastapi-app
