name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main  # Можете изменить на нужную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Использует последнюю версию Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Клонирует репозиторий

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Настройка для использования Docker Buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: m0ln1z/my-fastapi-app:latest  # Убедитесь, что тег правильный

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Дождаться завершения сборки перед деплоем

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: SSH into server and deploy Docker container
      run: |
        ssh -o StrictHostKeyChecking=no ${SERVER_USERNAME}@${SERVER_HOST} << 'EOF
          docker pull m0ln1z/my-fastapi-app:latest 
          docker stop my-fastapi-app || true  
          docker rm my-fastapi-app || true  
          docker run -d --name my-fastapi-app -p 80:80 m0ln1z/my-fastapi-app:latest  
        EOF
