name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Установка Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Построение Docker образа
      - name: Build Docker image
        run: docker build -t my-fastapi-app .

      # Публикация Docker образа в Docker Hub (если нужно)
      - name: Push Docker image to Docker Hub
        run: docker push my-fastapi-app

      # Установка SSH ключа для доступа к серверу
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Деплой на сервер
      - name: Deploy to server
        run: |
          # Подключаемся к серверу через SSH и перезапускаем контейнер
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Останавливаем и удаляем старый контейнер (если существует)
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            # Загружаем последний образ из Docker Hub
            docker pull my-fastapi-app

            # Запускаем новый контейнер
            docker run -d -p 8000:8000 --name fastapi-app my-fastapi-app
          EOF
